### ISSUE TITLE
Function version of this?

### ISSUE THREAD

**Issue by twhughes** [alisaaalehi/convolution_as_multiplication#1]
First of all thanks so much for this!  It's extremely useful!

I'm wondering if you have this available as a python function. That takes a convolution kernel and returns a sparse matrix. For example:

```python
def get_sparse(filter):
     # computes the sparse matrix corresponding to convolution with filter
```

Specifically, I'm trying to implement something similar for a 3D convolution, for example if your kernel is a 3D numpy array

```python
kernel = np.array([[[1, -1], [-1, 1]], [[1, -1], [-1, 1]]])
```

I've been trying to translate your notebook in a function but figured maybe you had this somewhere already.

Thanks so much!

**Comment by alisaaalehi** [comment]
Hi @twhughes, could you explain more? What do you mean by` get_sparse()`? You want this function to take the initial filter and return the _doubly_blocked_ matrix?

**Comment by twhughes** [comment]
Thanks for your response @alisaaalehi.  Yes, basically the function would take the filter (in any dimension), perhaps as a numpy array, and return the doubly blocked matrix.  Do you think this is possible?

**Comment by alisaaalehi** [comment]
Yeah, It is easy. You can copy the pieces of code from the notebook file and put them in a function. 
As you can see from the steps of the algorithm, you need to pass the shape of the input signal to your  `get_sparse()` function too.
For the 3D case (if your data and filters are 3D), I don't think the exact same code will work! But you are welcome to generalize the code and make a pull request.

**Comment by twhughes** [comment]
Ok thanks.  I wasnt sure how to generalize the code to 3D but I'll give it a go.  Thanks for your help!
